spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

grpc:
  client:
    hub-router:
      address: 'discovery:///hub-router'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    topics:
      snapshots: telemetry.snapshots.v1
      hubs: telemetry.hubs.v1
    consumer:
      snapshots:
        group-id: analyzer-snapshots-group
        client-id: analyzer-snapshots-consumer
        enable-auto-commit: false
      hubs:
        group-id: analyzer-hubs-group
        client-id: analyzer-hubs-consumer
        enable-auto-commit: true

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.apache.kafka: WARN